from flask_restx import fields
from payana.payana_bl.bigtable_utils.constants import bigtable_constants

payana_profile_table_profile_name = bigtable_constants.payana_profile_table_profile_name
payana_profile_table_user_name = bigtable_constants.payana_profile_table_user_name
payana_profile_table_blog_url = bigtable_constants.payana_profile_table_blog_url
payana_profile_table_profile_description = bigtable_constants.payana_profile_table_profile_description
payana_profile_table_profile_id = bigtable_constants.payana_profile_table_profile_id
payana_profile_table_email = bigtable_constants.payana_profile_table_email
payana_profile_table_phone = bigtable_constants.payana_profile_table_phone
payana_profile_table_private_account = bigtable_constants.payana_profile_table_private_account
payana_profile_table_gender = bigtable_constants.payana_profile_table_gender
payana_profile_table_date_of_birth = bigtable_constants.payana_profile_table_date_of_birth
payana_profile_table_doj = bigtable_constants.payana_profile_table_doj

payana_profile_table_personal_info_column_family = bigtable_constants.payana_profile_table_personal_info_column_family
payana_profile_table_top_activities_tracker_rating = bigtable_constants.payana_profile_table_top_activities_tracker_rating
payana_profile_favorite_places_preference = bigtable_constants.payana_profile_favorite_places_preference
payana_profile_favorite_activities_preference = bigtable_constants.payana_profile_favorite_activities_preference
payana_profile_table_thumbnail_travel_buddies = bigtable_constants.payana_profile_table_thumbnail_travel_buddies


