autocomplete_android_api_key_config_file = "/Users/abhinandankelgereramesh/Documents/payana-github/TravelFont/payana/payana_core/autocomplete_utils/config/android_autocomplete_api_key.txt"
autocomplete_darwin_api_key_config_file = "/Users/abhinandankelgereramesh/Documents/payana-github/TravelFont/payana/payana_core/autocomplete_utils/config/darwin_autocomplete_api_key.txt"
autocomplete_web_api_key_config_file = "/Users/abhinandankelgereramesh/Documents/payana-github/TravelFont/payana/payana_core/autocomplete_utils/config/web_autocomplete_api_key.txt"
